server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: pizzaordermanagement
          uri: http://localhost:8081
          predicates:
            - Path=/pizzaOrders/** 
        - id: paymentmanagement
          uri: http://localhost:8082
          predicates:
            - Path=/paymentHistories/** 
        - id: notificationmanagement
          uri: http://localhost:8083
          predicates:
            - Path=/notificationHistories/** 
        - id: satisfactionmanagement
          uri: http://localhost:8084
          predicates:
            - Path=/satisfactions/** 
        - id: orderdeliverymanagement
          uri: http://localhost:8085
          predicates:
            - Path=/orderDeliveries/** 
        - id: marketingmanagement
          uri: http://localhost:8086
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: pizzaordermanagement
          uri: http://pizzaordermanagement:8080
          predicates:
            - Path=/pizzaOrders/** 
        - id: paymentmanagement
          uri: http://paymentmanagement:8080
          predicates:
            - Path=/paymentHistories/** 
        - id: notificationmanagement
          uri: http://notificationmanagement:8080
          predicates:
            - Path=/notificationHistories/** 
        - id: satisfactionmanagement
          uri: http://satisfactionmanagement:8080
          predicates:
            - Path=/satisfactions/** 
        - id: orderdeliverymanagement
          uri: http://orderdeliverymanagement:8080
          predicates:
            - Path=/orderDeliveries/** 
        - id: marketingmanagement
          uri: http://marketingmanagement:8080
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
